# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
np.__version__
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prafu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prafu/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prafu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prafu/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prafu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prafu/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/prafu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/prafu/anaconda3\\Library\\include']


#### 3. Create a null vector of size 10

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [22]:
x = np.array([100, 20, 34])
  
print("Memory size of a NumPy array:",
      x.nbytes)

Memory size of a NumPy array: 12


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [6]:
import numpy
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [4]:
null = np.zeros(10)
null[4]=1

#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [8]:
b = np.arange(10,50)

b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
c = np.arange(0,9)

c.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [28]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print (nz)


(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [11]:
np.identity(3)
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [13]:
np.random.random((3, 3, 3))

array([[[0.14162835, 0.28722301, 0.3154331 ],
        [0.75304259, 0.16974365, 0.20069366],
        [0.77465186, 0.15660526, 0.30019632]],

       [[0.30133847, 0.70614737, 0.31266942],
        [0.13030778, 0.46316009, 0.92989979],
        [0.30246765, 0.56186259, 0.29522438]],

       [[0.63876908, 0.22980312, 0.20767775],
        [0.34609688, 0.37934853, 0.86499833],
        [0.04498989, 0.9011631 , 0.70125748]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [15]:
e = np.random.random((10,10))
np.min(e)

np.max(e)

0.9953370782973793

#### 14. Create a random vector of size 30 and find the mean value

In [16]:
f = np.random.random((5,6))

np.mean(f)

0.476984491259094

#### 15. Create a 2d array with 1 on the border and 0 inside

In [19]:
g = np.ones((5,5))

g[1:4, 1:4] = 0


#### 16. How to add a border (filled with 0's) around an existing array?

In [20]:
h = np.ones((5,5))

h[:1, :] = 0

h[:, :1] = 0

h[4:, :] = 0

h[:, 4:] = 0

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

## False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [29]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [30]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [31]:
print (np.unravel_index(100, (6,7,8)))


(1, 5, 4)
